import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import {
  careers,
  careerSnapshots,
  playerSnapshots,
  clubFinanceSnapshots,
  players,
  clubFinances,
  playerUserProfiles,
  careerEvents,
  managerOnboardingProfiles,
  tacticalSystems,
} from "@/lib/db/schema";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const EXPORTS_DIR = path.join(process.cwd(), "data", "exports");

/** Filesystem-safe timestamp: 2026-09-27T14-05-33-123Z */
function timestampSlug(): string {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

/**
 * GET /api/career/export?careerId=...
 *
 * Writes a complete JSON backup of one career to `data/exports/` and returns its location.
 * This exists so the destructive Reset action always has a recoverable artefact beside it -
 * a cascade delete removes nine tables and cannot be undone from the UI.
 */
export async function GET(request: Request) {
  const careerId = new URL(request.url).searchParams.get("careerId");
  if (!careerId) {
    return NextResponse.json(
      { success: false, error: "careerId parameter is required." },
      { status: 400 }
    );
  }

  try {
    const career = await db.select().from(careers).where(eq(careers.id, careerId)).get();
    if (!career) {
      return NextResponse.json(
        { success: false, error: `Career ${careerId} not found.` },
        { status: 404 }
      );
    }

    const [
      snapshotRows,
      playerSnapshotRows,
      financeSnapshotRows,
      playerRows,
      financeRow,
      profileRows,
      onboardingRow,
      tacticsRow,
      eventRows,
    ] = await Promise.all([
      db.select().from(careerSnapshots).where(eq(careerSnapshots.careerId, careerId)),
      db.select().from(playerSnapshots).where(eq(playerSnapshots.careerId, careerId)),
      db.select().from(clubFinanceSnapshots).where(eq(clubFinanceSnapshots.careerId, careerId)),
      db.select().from(players).where(eq(players.careerId, careerId)),
      db.select().from(clubFinances).where(eq(clubFinances.careerId, careerId)).get(),
      db.select().from(playerUserProfiles).where(eq(playerUserProfiles.careerId, careerId)),
      db
        .select()
        .from(managerOnboardingProfiles)
        .where(eq(managerOnboardingProfiles.careerId, careerId))
        .get(),
      db.select().from(tacticalSystems).where(eq(tacticalSystems.careerId, careerId)).get(),
      db.select().from(careerEvents).where(eq(careerEvents.careerId, careerId)),
    ]);

    const payload = {
      schemaVersion: 1,
      exportedAt: new Date().toISOString(),
      // Provenance legend travels with the data so an exported file is self-describing.
      provenanceLegend: {
        SAVE: "Parsed from your career save file.",
        USER: "Entered by the manager.",
        DERIVED: "Computed by TouchlineOS from saved facts.",
        AI: "Generated by a language model (no AI features exist yet).",
      },
      career,
      counts: {
        snapshots: snapshotRows.length,
        playerSnapshots: playerSnapshotRows.length,
        clubFinanceSnapshots: financeSnapshotRows.length,
        players: playerRows.length,
        careerEvents: eventRows.length,
        playerUserProfiles: profileRows.length,
      },
      snapshots: snapshotRows,
      playerSnapshots: playerSnapshotRows,
      clubFinanceSnapshots: financeSnapshotRows,
      players: playerRows,
      clubFinances: financeRow ?? null,
      playerUserProfiles: profileRows,
      onboarding: onboardingRow ?? null,
      tacticalSystems: tacticsRow ?? null,
      careerEvents: eventRows,
    };

    fs.mkdirSync(EXPORTS_DIR, { recursive: true });
    const fileName = `${careerId}_${timestampSlug()}.json`;
    const filePath = path.join(EXPORTS_DIR, fileName);
    fs.writeFileSync(filePath, JSON.stringify(payload, null, 2), "utf8");

    return NextResponse.json({
      success: true,
      careerId,
      fileName,
      filePath,
      sizeBytes: fs.statSync(filePath).size,
      counts: payload.counts,
    });
  } catch (error) {
    console.error("[api/career/export] failed:", error);
    return NextResponse.json(
      { success: false, error: (error as Error).message ?? "Export failed." },
      { status: 500 }
    );
  }
}
