/**
 * Career transfer: a one-time, user-initiated export/import of ONE career.
 *
 * This is deliberately NOT a sync mechanism and not a shared file. The local build writes a backup
 * to `data/exports/`; the user then hands that single file to another build (a browser, another
 * desktop). Nothing here reads a path it was not given, and nothing transfers automatically.
 *
 * The format is the one `/api/career/export` has always produced (`schemaVersion: 1`), so a backup
 * written before this module existed imports unchanged.
 */
import { eq } from "drizzle-orm";
import { db } from "../db/client";
import { storage } from "../platform/storage";
import {
  careers,
  careerSnapshots,
  playerSnapshots,
  clubFinanceSnapshots,
  players,
  clubFinances,
  playerUserProfiles,
  careerEvents,
  managerOnboardingProfiles,
  tacticalSystems,
} from "../db/schema";

/** Raised for a payload that is not a readable backup. Surfaces as a 400, not a 500. */
export class TransferPackageError extends Error {}

/** The on-wire shape of a career backup. */
export interface CareerTransferPackage {
  schemaVersion: number;
  exportedAt: string;
  provenanceLegend?: Record<string, string>;
  career: typeof careers.$inferSelect;
  counts?: Record<string, number>;
  snapshots: (typeof careerSnapshots.$inferSelect)[];
  playerSnapshots: (typeof playerSnapshots.$inferSelect)[];
  clubFinanceSnapshots: (typeof clubFinanceSnapshots.$inferSelect)[];
  players: (typeof players.$inferSelect)[];
  clubFinances: typeof clubFinances.$inferSelect | null;
  playerUserProfiles: (typeof playerUserProfiles.$inferSelect)[];
  onboarding: typeof managerOnboardingProfiles.$inferSelect | null;
  tacticalSystems: typeof tacticalSystems.$inferSelect | null;
  careerEvents: (typeof careerEvents.$inferSelect)[];
}

/** The package version this build reads and writes. */
export const TRANSFER_SCHEMA_VERSION = 1;

/**
 * Reads one career into a transfer package, or null when there is no such career.
 *
 * The shape is exactly what `/api/career/export` has always written - same keys, same provenance
 * legend - so existing backups and existing consumers both keep working.
 */
export async function buildTransferPackage(
  careerId: string
): Promise<CareerTransferPackage | null> {
  const career = await db.select().from(careers).where(eq(careers.id, careerId)).get();
  if (!career) return null;

  const [
    snapshotRows,
    playerSnapshotRows,
    financeSnapshotRows,
    playerRows,
    financeRow,
    profileRows,
    onboardingRow,
    tacticsRow,
    eventRows,
  ] = await Promise.all([
    db.select().from(careerSnapshots).where(eq(careerSnapshots.careerId, careerId)),
    db.select().from(playerSnapshots).where(eq(playerSnapshots.careerId, careerId)),
    db.select().from(clubFinanceSnapshots).where(eq(clubFinanceSnapshots.careerId, careerId)),
    db.select().from(players).where(eq(players.careerId, careerId)),
    db.select().from(clubFinances).where(eq(clubFinances.careerId, careerId)).get(),
    db.select().from(playerUserProfiles).where(eq(playerUserProfiles.careerId, careerId)),
    db
      .select()
      .from(managerOnboardingProfiles)
      .where(eq(managerOnboardingProfiles.careerId, careerId))
      .get(),
    db.select().from(tacticalSystems).where(eq(tacticalSystems.careerId, careerId)).get(),
    db.select().from(careerEvents).where(eq(careerEvents.careerId, careerId)),
  ]);

  return {
    schemaVersion: TRANSFER_SCHEMA_VERSION,
    exportedAt: new Date().toISOString(),
    // Provenance legend travels with the data so an exported file is self-describing.
    provenanceLegend: {
      SAVE: "Parsed from your career save file.",
      USER: "Entered by the manager.",
      DERIVED: "Computed by TouchlineOS from saved facts.",
      AI: "Generated by a language model (no AI features exist yet).",
    },
    career,
    counts: {
      snapshots: snapshotRows.length,
      playerSnapshots: playerSnapshotRows.length,
      clubFinanceSnapshots: financeSnapshotRows.length,
      players: playerRows.length,
      careerEvents: eventRows.length,
      playerUserProfiles: profileRows.length,
    },
    snapshots: snapshotRows,
    playerSnapshots: playerSnapshotRows,
    clubFinanceSnapshots: financeSnapshotRows,
    players: playerRows,
    clubFinances: financeRow ?? null,
    playerUserProfiles: profileRows,
    onboarding: onboardingRow ?? null,
    tacticalSystems: tacticsRow ?? null,
    careerEvents: eventRows,
  };
}

export interface TransferImportSummary {
  careerId: string;
  imported: Record<string, number>;
}

function asRows<T>(value: unknown): T[] {
  return Array.isArray(value) ? (value as T[]) : [];
}

/** Validates an untrusted payload into a package, or throws `TransferPackageError`. */
function assertPackage(payload: unknown): CareerTransferPackage {
  if (!payload || typeof payload !== "object") {
    throw new TransferPackageError("That file is not a TouchlineOS career backup.");
  }

  const raw = payload as Record<string, unknown>;
  if (raw.schemaVersion !== TRANSFER_SCHEMA_VERSION) {
    throw new TransferPackageError(
      `Unsupported backup version: ${String(raw.schemaVersion)}. This build reads version ${TRANSFER_SCHEMA_VERSION}.`
    );
  }

  const career = raw.career as { id?: unknown } | undefined;
  if (!career || typeof career !== "object" || typeof career.id !== "string" || career.id === "") {
    throw new TransferPackageError("That backup has no career id, so there is nothing to import.");
  }

  return {
    schemaVersion: TRANSFER_SCHEMA_VERSION,
    exportedAt: typeof raw.exportedAt === "string" ? raw.exportedAt : new Date().toISOString(),
    provenanceLegend: (raw.provenanceLegend as Record<string, string> | undefined) ?? undefined,
    career: raw.career as CareerTransferPackage["career"],
    counts: raw.counts as Record<string, number> | undefined,
    snapshots: asRows(raw.snapshots),
    playerSnapshots: asRows(raw.playerSnapshots),
    clubFinanceSnapshots: asRows(raw.clubFinanceSnapshots),
    players: asRows(raw.players),
    clubFinances: (raw.clubFinances as CareerTransferPackage["clubFinances"]) ?? null,
    playerUserProfiles: asRows(raw.playerUserProfiles),
    onboarding: (raw.onboarding as CareerTransferPackage["onboarding"]) ?? null,
    tacticalSystems: (raw.tacticalSystems as CareerTransferPackage["tacticalSystems"]) ?? null,
    careerEvents: asRows(raw.careerEvents),
  };
}

/** Raised when the target already holds this career. Surfaces as a 409, not a 400. */
export class CareerAlreadyPresentError extends Error {}

/**
 * Applies a backup, inserting the career it names.
 *
 * Import refuses when this career already exists. That is a deliberate safety choice, not a
 * limitation of effort: this format carries 9 of the 25 career-scoped tables, and several of the
 * tables it does NOT carry hang off the ones it does by cascading foreign keys (storyline evidence
 * off `career_events`, league tables and season progress off `career_snapshots`). Clearing the nine
 * to reinsert them would therefore silently take the other sixteen with it. Refusing keeps an
 * import from ever destroying data it cannot restore; replacing an existing career stays a
 * deliberate, separate action.
 */
export async function importTransferPackage(
  payload: unknown
): Promise<TransferImportSummary> {
  const pkg = assertPackage(payload);
  const careerId = pkg.career.id;

  const imported = storage.withTransaction((tx) => {
    const existing = tx
      .select({ id: careers.id })
      .from(careers)
      .where(eq(careers.id, careerId))
      .get();
    if (existing) {
      throw new CareerAlreadyPresentError(
        `This career (${careerId}) already exists here. Delete it first if you want to replace it - this backup does not carry every career-scoped table, so importing over it would discard the rest.`
      );
    }

    // Parent before children, and career_snapshots before anything that references it, so the
    // foreign keys are satisfied by construction.
    tx.insert(careers).values(pkg.career).run();
    if (pkg.snapshots.length) tx.insert(careerSnapshots).values(pkg.snapshots).run();
    if (pkg.playerSnapshots.length) tx.insert(playerSnapshots).values(pkg.playerSnapshots).run();
    if (pkg.clubFinanceSnapshots.length) {
      tx.insert(clubFinanceSnapshots).values(pkg.clubFinanceSnapshots).run();
    }
    if (pkg.players.length) tx.insert(players).values(pkg.players).run();
    if (pkg.playerUserProfiles.length) {
      tx.insert(playerUserProfiles).values(pkg.playerUserProfiles).run();
    }
    if (pkg.careerEvents.length) tx.insert(careerEvents).values(pkg.careerEvents).run();
    if (pkg.clubFinances) tx.insert(clubFinances).values(pkg.clubFinances).run();
    if (pkg.onboarding) tx.insert(managerOnboardingProfiles).values(pkg.onboarding).run();
    if (pkg.tacticalSystems) tx.insert(tacticalSystems).values(pkg.tacticalSystems).run();

    return {
      snapshots: pkg.snapshots.length,
      playerSnapshots: pkg.playerSnapshots.length,
      clubFinanceSnapshots: pkg.clubFinanceSnapshots.length,
      players: pkg.players.length,
      playerUserProfiles: pkg.playerUserProfiles.length,
      careerEvents: pkg.careerEvents.length,
      clubFinances: pkg.clubFinances ? 1 : 0,
      onboarding: pkg.onboarding ? 1 : 0,
      tacticalSystems: pkg.tacticalSystems ? 1 : 0,
    };
  });

  return { careerId, imported };
}
