/**
 * Face rules and fetching, shared by both runtimes.
 *
 * Deliberately free of `fs`, `path` and the database: the local build caches sprites in
 * `public/faces/` and the browser build caches them in OPFS, but *which* players have a face, which
 * ids the game generated, and what counts as a sprite rather than the CDN's error page are the same
 * questions in both. Only the storage differs, and that is the `FaceSink` this takes.
 *
 * The CDN is keyed by EA's internal playerid, which is exactly our `players.ea_player_id`, so no
 * mapping table is needed.
 */

export const FACE_CDN_BASE = "https://cdn.futwiz.com/assets/img/fc26/faces";

/** Anything smaller than this is the CDN's error page rather than a player's face. */
export const MIN_SPRITE_BYTES = 500;

/** Players at or above this id are generated by the game and have no real face. */
export const NEWGEN_ID_FLOOR = 400_000;

const FETCH_TIMEOUT_MS = 8_000;

/** Modest concurrency: enough to be quick, low enough not to look like abuse. */
const FACE_CONCURRENCY = 6;

/** The file one player's sprite lives in, wherever this runtime caches it. */
export function faceFileName(eaPlayerId: number): string {
  return `${eaPlayerId}.png`;
}

/** False for ids that cannot name a real player, so no request is worth making. */
export function isUsablePlayerId(eaPlayerId: number): boolean {
  return Number.isFinite(eaPlayerId) && eaPlayerId > 0;
}

/** Players at or above `NEWGEN_ID_FLOOR` are game-generated and have no sprite anywhere. */
export function isNewgen(eaPlayerId: number): boolean {
  return eaPlayerId >= NEWGEN_ID_FLOOR;
}

export type SpriteOutcome = "sprite" | "no-sprite" | "newgen";

export interface SpriteResult {
  outcome: SpriteOutcome;
  bytes: Uint8Array | null;
}

/**
 * Asks the CDN for one sprite.
 *
 * Two guards decide "no sprite", and both are kept. The status check catches the clean 404 the CDN
 * returns for an id it does not have; the size check catches the other shape it has been seen to
 * return, a small error-page image served with a 200. Real sprites measure 7.6-9.0 KB, so neither
 * check alone is enough.
 */
export async function fetchSprite(eaPlayerId: number): Promise<SpriteResult> {
  const missing: SpriteResult = { outcome: "no-sprite", bytes: null };
  if (!isUsablePlayerId(eaPlayerId)) return missing;
  if (isNewgen(eaPlayerId)) return { outcome: "newgen", bytes: null };

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const response = await fetch(`${FACE_CDN_BASE}/${eaPlayerId}.png`, {
      signal: controller.signal,
      // A browser silently drops this (User-Agent is a forbidden header there); Node sends it. Let
      // one header list serve both rather than branching on which runtime is asking.
      headers: { "User-Agent": "TouchlineOS/0.1 (local companion)" },
    });
    if (!response.ok) return missing;

    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength < MIN_SPRITE_BYTES) return missing;

    return { outcome: "sprite", bytes };
  } catch {
    // A timeout or a network failure is not evidence that the player has no face, so this is
    // reported as "no sprite" and the player falls back to initials until a later run.
    return missing;
  } finally {
    clearTimeout(timer);
  }
}

async function runWithConcurrency<T>(
  items: T[],
  limit: number,
  worker: (item: T) => Promise<void>
): Promise<void> {
  let cursor = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor++;
      await worker(items[index]);
    }
  });
  await Promise.all(runners);
}

export interface FaceImportSummary {
  total: number;
  cached: number;
  fetched: number;
  noSprite: number;
  newgen: number;
  errors: number;
}

/** Where a runtime keeps the sprites it has already resolved. */
export interface FaceSink {
  has(eaPlayerId: number): boolean | Promise<boolean>;
  write(eaPlayerId: number, bytes: Uint8Array): Promise<void>;
}

/**
 * Resolves faces for a list of players, using `sink` as the cache.
 *
 * Idempotent by construction: a player the sink already holds costs one lookup and no request, so
 * this is safe to run on every sync - which is exactly what keeps a new signing's face arriving on
 * its own, with nothing for the manager to press.
 */
export async function cacheFaces(
  eaPlayerIds: number[],
  sink: FaceSink
): Promise<FaceImportSummary> {
  const summary: FaceImportSummary = {
    total: eaPlayerIds.length,
    cached: 0,
    fetched: 0,
    noSprite: 0,
    newgen: 0,
    errors: 0,
  };

  await runWithConcurrency(eaPlayerIds, FACE_CONCURRENCY, async (eaPlayerId) => {
    try {
      // Checked in this order so a newgen is always reported as a newgen: it is a fact about the
      // player, not a failure to find a file, and the two are worth telling apart in the summary.
      if (!isUsablePlayerId(eaPlayerId)) {
        summary.noSprite += 1;
        return;
      }
      if (isNewgen(eaPlayerId)) {
        summary.newgen += 1;
        return;
      }
      if (await sink.has(eaPlayerId)) {
        summary.cached += 1;
        return;
      }

      const sprite = await fetchSprite(eaPlayerId);
      if (sprite.outcome === "newgen") {
        summary.newgen += 1;
        return;
      }
      if (!sprite.bytes) {
        summary.noSprite += 1;
        return;
      }

      await sink.write(eaPlayerId, sprite.bytes);
      summary.fetched += 1;
    } catch {
      summary.errors += 1;
    }
  });

  return summary;
}
