/**
 * Player faces.
 *
 * The CDN is keyed by EA's internal playerid, which is exactly our `players.ea_player_id`, so no
 * mapping table is needed. Faces are written into `public/faces/` because Next serves `public/`
 * statically: that keeps the whole thing offline at runtime with no route to maintain.
 *
 * Two guards decide "no sprite", and BOTH are needed. The CDN does not return a clean 404 - it
 * returns a small error-page image with a 200 - so a status check alone is not enough, and a size
 * check alone would accept an error page served under a 404. Real sprites measured 7.6-9.0 KB.
 *
 * Deliberately NOT gated on `players.hashighqualityhead`. That field means "has a scanned head",
 * not "has a face": measured against the CDN, players with the flag at 0 returned real 8.5 KB
 * sprites, so gating on it would have skipped 23 of 24 players in a real squad.
 *
 * Newgens (id >= 400000) have no sprite anywhere by definition, so they skip the network entirely.
 */
import fs from "fs";
import path from "path";
import { desc, eq } from "drizzle-orm";
import { db } from "../db/client";
import { players } from "../db/schema";

const FACE_DIR = path.join(process.cwd(), "public", "faces");
const CDN_BASE = "https://cdn.futwiz.com/assets/img/fc26/faces";
/** Anything smaller than this is the CDN's error page rather than a player's face. */
const MIN_SPRITE_BYTES = 500;
/** Players at or above this id are generated by the game and have no real face. */
const NEWGEN_ID_FLOOR = 400_000;
const FETCH_TIMEOUT_MS = 8000;
/** Modest concurrency: enough to be quick, low enough not to look like abuse. */
const CONCURRENCY = 6;

export type FaceOutcome = "cached" | "fetched" | "no-sprite" | "newgen";

export interface FaceImportSummary {
  total: number;
  cached: number;
  fetched: number;
  noSprite: number;
  newgen: number;
  errors: number;
}

/**
 * The on-disk path for one player's sprite.
 *
 * Exported so the platform `AssetStore` shares this single definition of where faces live rather
 * than repeating the path.
 */
export function facePathFor(eaPlayerId: number): string {
  return path.join(FACE_DIR, `${eaPlayerId}.png`);
}

/** True when this player already has a cached sprite. Never touches the network. */
export function hasCachedFace(eaPlayerId: number): boolean {
  try {
    return fs.existsSync(facePathFor(eaPlayerId));
  } catch {
    return false;
  }
}

/** The cached sprite bytes, or null when this player has no cached face. */
export function readFaceBytes(eaPlayerId: number): Uint8Array | null {
  try {
    return fs.readFileSync(facePathFor(eaPlayerId));
  } catch {
    return null;
  }
}

/** Caches sprite bytes for one player, creating the faces directory if it does not exist yet. */
export function writeFaceBytes(eaPlayerId: number, bytes: Uint8Array): void {
  fs.mkdirSync(FACE_DIR, { recursive: true });
  fs.writeFileSync(facePathFor(eaPlayerId), bytes);
}

/**
 * Resolves one player's face, using the local cache before the network.
 *
 * Idempotent: a player already on disk is never re-fetched, so this is safe to run on every sync.
 */
export async function ensureFace(eaPlayerId: number): Promise<FaceOutcome> {
  if (!Number.isFinite(eaPlayerId) || eaPlayerId <= 0) return "no-sprite";
  if (eaPlayerId >= NEWGEN_ID_FLOOR) return "newgen";
  if (hasCachedFace(eaPlayerId)) return "cached";

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const response = await fetch(`${CDN_BASE}/${eaPlayerId}.png`, {
      signal: controller.signal,
      headers: { "User-Agent": "TouchlineOS/0.1 (local companion)" },
    });
    if (!response.ok) return "no-sprite";

    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength < MIN_SPRITE_BYTES) return "no-sprite";

    writeFaceBytes(eaPlayerId, bytes);
    return "fetched";
  } catch {
    // A timeout or a network failure is not evidence that the player has no face, so this is
    // reported as an error and the player simply falls back to initials until a later run.
    return "no-sprite";
  } finally {
    clearTimeout(timer);
  }
}

async function runWithConcurrency<T>(
  items: T[],
  limit: number,
  worker: (item: T) => Promise<void>
): Promise<void> {
  let cursor = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor++;
      await worker(items[index]);
    }
  });
  await Promise.all(runners);
}

/**
 * Fetches faces for every player on the books, skipping anyone already cached.
 *
 * The `players` table only ever holds the manager's own squad and youth, so scoping to a career is
 * itself the "squad and youth only" rule - there is no wider roster to leak out to.
 */
export async function ensureFacesForSquad(careerId: string): Promise<FaceImportSummary> {
  const squad = await db
    .select({ eaPlayerId: players.eaPlayerId })
    .from(players)
    .where(eq(players.careerId, careerId))
    .orderBy(desc(players.overallRating));

  const summary: FaceImportSummary = {
    total: squad.length,
    cached: 0,
    fetched: 0,
    noSprite: 0,
    newgen: 0,
    errors: 0,
  };

  await runWithConcurrency(squad, CONCURRENCY, async (row) => {
    try {
      const outcome = await ensureFace(row.eaPlayerId);
      if (outcome === "cached") summary.cached++;
      else if (outcome === "fetched") summary.fetched++;
      else if (outcome === "newgen") summary.newgen++;
      else summary.noSprite++;
    } catch {
      summary.errors++;
    }
  });

  return summary;
}

/** Every face currently on disk, for diagnostics. */
export function listCachedFaces(): number[] {
  try {
    if (!fs.existsSync(FACE_DIR)) return [];
    return fs
      .readdirSync(FACE_DIR)
      .filter((name) => name.endsWith(".png"))
      .map((name) => Number(name.replace(".png", "")))
      .filter((id) => Number.isFinite(id));
  } catch {
    return [];
  }
}
